### ISSUE TITLE
Uncaught TypeError: handlers[index] is not a function

### ISSUE THREAD

**Issue by PEM--** [brigade/react-waypoint#126] opened 2016-10-20 07:44 UTC
This appeared when I've updated to `4.0.0`.
![capture d ecran 2016-10-20 a 09 42 00](https://cloud.githubusercontent.com/assets/227831/19550427/9d43e2be-96a9-11e6-9016-0ac04b3a5b45.png)

**Comment by trotzig** [comment] 2016-10-20 08:27
Thanks for the report @PEM--, I'm looking into it. Can you share a little bit more about how you use react-waypoint? Are you for instance using `throttleHandler`?

**Comment by PEM--** [comment] 2016-10-20 08:31
It's me that is thanking you for sharing this nice component.

I've used with and without the `throttleHandler`. Same problem in both cases. Recently, I've added the `fireOnRapidScroll`. Not sure if it's related.

**Comment by trotzig** [comment] 2016-10-20 08:35
Probably not. I think this is caused by a race condition between handling a scroll/resize event and removing/unmounting a waypoint. I'm closing in on a fix.

**Comment by trotzig** [comment] 2016-10-20 09:03
Okay, I think I found it. I have a solution in mind that I hope to push in a short while.

**Comment by PEM--** [comment] 2016-10-20 09:12
👍

**Closed** 2016-10-20 09:22 UTC

**Comment by trotzig** [comment] 2016-10-20 09:38
I just pushed version `4.0.1` with a fix for this error. Again, thanks!

**Comment by PEM--** [comment] 2016-10-20 09:54
It works like a charm 👍
