### ISSUE TITLE
Waypoint renders above results when building infinite scroll

### ISSUE THREAD

**Issue by mplis-jetsetter** [brigade/react-waypoint#131] opened 2016-10-26 19:59 UTC
I'm attempting to use react-waypoint to implement infinite scroll, similar to the example on the [demo](http://brigade.github.io/react-waypoint/) page, but the demo seems to be broken and I'm running into the same issue in my code.

I assume the example is supposed to render the waypoint after the results and have new results render when you scroll to the bottom, which is the behavior I want in my app. However, the waypoint renders above the results, meaning that new results are only loaded when you scroll to the top of the results, not the bottom.

**Comment by trotzig** [comment] 2016-10-26 20:10
Thanks for making me aware of this! It looks like the demo is broken on smaller screens. It's working as intended on larger screens. I'll need to investigate more, but in the meantime it's likely you could use a wrapping div with `display: block` as a workaround.

**Comment by mplis-jetsetter** [comment] 2016-10-26 20:14
I'm experiencing this issue on a fairly large screen. Thanks for the tip on the wrapping div, I'll give that a try.

**Comment by trotzig** [comment] 2016-10-27 07:48
I pushed an update to the demo page. It's in need of a bigger update, but in the meantime we'll at least have a working example. I appreciate the heads up!

**Comment by trotzig** [comment] 2016-11-14 10:16
Closing this with the assumption that you managed to get your waypoint to work correctly @mplis-jetsetter. Re-open if that wasn't the right call!

**Closed by trotzig** 2016-11-14 10:16 UTC
